type Grid {
  id: ID!
  rowOrder: [Int!]!
  columnOrder: [Int!]!
  squares: [Square!]!
  creator: User!
  createdAt: DateTime!
}

type Square {
  id: ID!
  gridId: ID!
  rowIndex: Int!
  columnIndex: Int!
  rowValue: Int!
  columnValue: Int!
  player: User
}

extend type Query {
  grid(id: ID!): Grid
}

input UpdateSquareInput {
  value: String
}

input AssignGridToGameInput {
  gridId: ID!
  gameId: ID!
}

extend type Mutation {
  createGrid: Grid!
  updateSquare(id: ID!, input: UpdateSquareInput!): Square
  assignGridToGame(input: AssignGridToGameInput!): Game
}
