scalar DateTime

type User {
  id: ID!
  firebaseUserId: String
  email: String
  phoneNumber: String
  displayName: String
  createdAt: DateTime!
  updatedAt: DateTime!
  ownedGrids: [Grid!]!
  playerGames: [GamePlayer!]!
}

input CreateUserInput {
  firebaseUserId: String
  email: String
  phoneNumber: String
  displayName: String
}

input UpdateUserInput {
  email: String
  phoneNumber: String
  displayName: String
}

type Query {
  hello: String!
  dbStatus: String!
  user(id: ID!): User
  userByFirebaseId(firebaseUserId: String!): User
  userByEmail(email: String!): User
  userByPhoneNumber(phoneNumber: String!): User
  users: [User!]!
  me: User
}

type Mutation {
  createUser(input: CreateUserInput!): User!
  updateUser(id: ID!, input: UpdateUserInput!): User
  deleteUser(id: ID!): Boolean!
}
