enum GameUserRole {
  PLAYER
  OWNER
}

type Game {
  id: ID!
  name: String!
  description: String
  createdAt: DateTime!
  updatedAt: DateTime!
  owners: [User!]!
  players: [GamePlayer!]!
  grid: Grid
}

type TempPlayer {
  id: ID!
  firstName: String!
  lastName: String!
  email: String
  phoneNumber: String
}

type GamePlayer {
  id: ID!
  gameId: String!
  userId: String
  tempUserId: String
  joinedAt: DateTime!
  game: Game!
  user: User
  tempPlayer: TempPlayer
  email: String
  phoneNumber: String
  fullName: String
  displayName: String
}

input CreateGameInput {
  name: String!
  description: String
}

input UpdateGameInput {
  name: String
  description: String
}

input AddUserToGameInput {
  gameId: ID!
  role: GameUserRole!
  email: String
  phoneNumber: String
}

input RemoveUserFromGameInput {
  gameId: ID!
  userId: ID!
  role: GameUserRole!
}

extend type Query {
  game(id: ID!): Game
  games: [Game!]!
  myGames: [Game!]!
}

input PlayerInput {
  firstName: String!
  lastName: String!
  email: String
  phoneNumber: String
}

input BulkAddPlayersInput {
  gameId: ID!
  players: [PlayerInput!]!
}

extend type Mutation {
  createGame(input: CreateGameInput!): Game!
  updateGame(id: ID!, input: UpdateGameInput!): Game
  deleteGame(id: ID!): Boolean!
  addUserToGame(input: AddUserToGameInput!): Game
  removeUserFromGame(input: RemoveUserFromGameInput!): Game
  bulkAddPlayers(input: BulkAddPlayersInput!): Game
}
